### ISSUE TITLE
On the blog page join slack button disabled

### ISSUE THREAD

**Issue by vardhanapoorv** [src-d/blog#168] opened 2017-12-08 01:39 UTC
On the blog page join slack button disabled Wanted to report bug also https://blog.sourced.tech/ on this page the place to enter the email id to join slack channel does not work that button does not work. OSX and chrome browser. When I press command key inside that text-box then only the button is enabled and clickable

<img width="847" alt="screen shot 2017-12-08 at 7 12 31 am" src="https://user-images.githubusercontent.com/13391028/33747004-9d2eb168-dbe6-11e7-8edf-8cce0e0f353c.png">

**Comment by dpordomingo** [comment] 2017-12-15 12:52
Thanks for reporting @vardhanapoorv !!
We're glad for your interest on us, and thanks for helping us to improve our blog!

I could not reproduce the bug.
Were you able to find a workaround to join our SlackChannel?

**Comment by dpordomingo** [comment] 2017-12-15 12:56
I found another issue https://github.com/src-d/blog/issues/169 providing more details about how to reproduce the bug, so updated this issue description with the https://github.com/src-d/blog/issues/169 title. 

We'll try to reproduce it that way :D

**Comment by vardhanapoorv** [comment] 2017-12-15 15:48
Yes I joined the slack channel through the home page since through blog page I wasn't able to

**Comment by dpordomingo** [comment] 2019-02-21 14:57
The migration to the new blogging platform is almost completed, so we're closing this issue because we are dropping this feature :desert_island:

**Closed by dpordomingo** 2019-02-21 14:57 UTC
Labels: bug, wontfix-legacy
