### ISSUE TITLE
What's wrong with the new blog

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/blog#282] opened 2019-03-20 15:01 UTC
This is the list of things I wish to be fixed in the new blog.sourced.tech:

- [x] all MSR interview header images show cut people. No eyes, no elbow, but nose and mouth in between 😄 
Example:
 
![Screenshot 2019-03-20 at 15 33 31](https://user-images.githubusercontent.com/2793551/54692657-a2e06980-4b25-11e9-9341-a94b9a1af5f0.png)

* https://blog.sourced.tech/post/msr-interview-5-jurgen-cito-and-gerald-schermann/
* https://blog.sourced.tech/post/msr-interview-4-sarah-nadi/
* https://blog.sourced.tech/post/msr-interview-3-vasiliki-efstathiou/
* https://blog.sourced.tech/post/msr-interview-2-georgios-gousios/
* https://blog.sourced.tech/post/msr-interview-1-abram-hindle/

- [x] @eiso's [FAQ post](https://blog.sourced.tech/post/top-10-questions-to-source-d-ceo-eiso-kant/) has text slides saved as JPEG, apparently looking terrible.

- [x] Titles of the migrated posts start with a lowercase letter. The Medium posts start with a capital letter.

- [x] The header images of the migrated posts were changed. Somehow nobody discussed those changes with me, and I chose the headers for my posts very carefully. Please return back my original header images.

- [x] The descriptions of all the migrated blog posts are invalid. They should be taken from the Markdown table at the top of each file. The current (wrong) text is the start of the post itself. Example:

![Screenshot 2019-03-20 at 15 45 06](https://user-images.githubusercontent.com/2793551/54693555-26e72100-4b27-11e9-8454-b4537e55bc55.png)

- [ ] When I click a post, it selects the whole block.

![Screenshot 2019-03-20 at 15 50 09](https://user-images.githubusercontent.com/2793551/54694002-dd4b0600-4b27-11e9-8723-b2315329d3ad.png)

- [x] Broken images

https://blog.sourced.tech/post/deduplicating_pga_with_apollo/#houston-we-have-a-problem

![Screenshot 2019-03-20 at 15 51 17](https://user-images.githubusercontent.com/2793551/54694131-04a1d300-4b28-11e9-9951-b8dde66d6942.png)

![Screenshot 2019-03-20 at 15 52 16](https://user-images.githubusercontent.com/2793551/54694211-27cc8280-4b28-11e9-8844-c54f1ae7301a.png)

The same problem in:

* https://blog.sourced.tech/post/hercules-v4/
* https://blog.sourced.tech/post/codesent/
* Everywhere actually

- [ ] Ugly tables

![Screenshot 2019-03-20 at 15 51 47](https://user-images.githubusercontent.com/2793551/54694180-18e5d000-4b28-11e9-80c0-86151c9d9b78.png)

![Screenshot 2019-03-20 at 15 52 47](https://user-images.githubusercontent.com/2793551/54694245-39ae2580-4b28-11e9-920d-4d1a15f7f370.png)

https://blog.sourced.tech/post/gld/
![Screenshot 2019-03-20 at 15 54 22](https://user-images.githubusercontent.com/2793551/54694381-72e69580-4b28-11e9-978c-be815c86b0fe.png)

- [ ] Ugly code blocks

https://blog.sourced.tech/post/gld/
![Screenshot 2019-03-20 at 15 55 08](https://user-images.githubusercontent.com/2793551/54694468-914c9100-4b28-11e9-8da7-1d3152996635.png)

- [ ] No height limit for the code blocks => no scroll

Spotted in https://blog.sourced.tech/post/gld/#rendering-and-normalization

- [ ] Formulas are images

This is really critical for ML team in particular. How are we supposed to edit the formulas?! This is a strict requirement for ML to write blog posts - we need mathjax or any other native math rendering.

Besides, they are displayed HUGE on my Mac.

- [ ] Problems with specific posts

https://blog.sourced.tech/post/id2vec/
![Screenshot 2019-03-20 at 15 57 50](https://user-images.githubusercontent.com/2793551/54694717-f607eb80-4b28-11e9-8e13-215bbb8ae7e3.png)

**Comment by ricardobaeta** [comment] 2019-03-20 15:05
Hi @vmarkovtsev a couple of enhancements are already up to under-review [here](https://github.com/src-d/feature-idea/issues/127), as well.

**Comment by vcoisne** [comment] 2019-04-08 18:39
Thanks a lot for your feedback @vmarkovtsev. @ricardobaeta and I have been working on solving these issues. Please find below my comments about the ones that are pending. 

> * [ ]  The header images of the migrated posts were changed. Somehow nobody discussed those changes with me, and I chose the headers for my posts very carefully. Please return back my original header images.

Sorry about that. I believe this was done to better fit the dimension of the featured image. Please let us know which one you'd like to update back to original header images.

> * [ ]  The descriptions of all the migrated blog posts are invalid. They should be taken from the Markdown table at the top of each file. The current (wrong) text is the start of the post itself. Example:
> 
> ![Screenshot 2019-03-20 at 15 45 06](https://user-images.githubusercontent.com/2793551/54693555-26e72100-4b27-11e9-8454-b4537e55bc55.png)

That's a default setting of Ghost and most blogging platform. I honestly don't think it is worth taking the time to update all the descriptions for all the posts.  

> * [ ]  When I click a post, it selects the whole block.
> 
> ![Screenshot 2019-03-20 at 15 50 09](https://user-images.githubusercontent.com/2793551/54694002-dd4b0600-4b27-11e9-8723-b2315329d3ad.png)

I can't reproduce this issue. Is this still an issue on your end ?

> * [ ]  Broken images
> 
> https://blog.sourced.tech/post/deduplicating_pga_with_apollo/#houston-we-have-a-problem
> 
> ![Screenshot 2019-03-20 at 15 51 17](https://user-images.githubusercontent.com/2793551/54694131-04a1d300-4b28-11e9-9951-b8dde66d6942.png)
> 
> ![Screenshot 2019-03-20 at 15 52 16](https://user-images.githubusercontent.com/2793551/54694211-27cc8280-4b28-11e9-8844-c54f1ae7301a.png)
> 
> The same problem in:
> 
> * https://blog.sourced.tech/post/hercules-v4/
> * https://blog.sourced.tech/post/codesent/
> * Everywhere actually

Fixed in most blog post minus https://blog.sourced.tech/post/announcing-pga/. The image are also missing from the archive version https://blog-archive.sourced.tech/post/announcing-pga/. Can you point me to the images and I can add them back ?

> * [ ]  Ugly tables
> 
> ![Screenshot 2019-03-20 at 15 51 47](https://user-images.githubusercontent.com/2793551/54694180-18e5d000-4b28-11e9-80c0-86151c9d9b78.png)
> 
> ![Screenshot 2019-03-20 at 15 52 47](https://user-images.githubusercontent.com/2793551/54694245-39ae2580-4b28-11e9-920d-4d1a15f7f370.png)
> 
> https://blog.sourced.tech/post/gld/
> ![Screenshot 2019-03-20 at 15 54 22](https://user-images.githubusercontent.com/2793551/54694381-72e69580-4b28-11e9-978c-be815c86b0fe.png)

Don't think it's worth investing the time to update. Minor added value for the readers. 
 
> * [ ]  Ugly code blocks
> 
> https://blog.sourced.tech/post/gld/
> ![Screenshot 2019-03-20 at 15 55 08](https://user-images.githubusercontent.com/2793551/54694468-914c9100-4b28-11e9-8da7-1d3152996635.png)
> 
> * [ ]  No height limit for the code blocks => no scroll
> 
> Spotted in https://blog.sourced.tech/post/gld/#rendering-and-normalization

Looks like this [post](https://hassannadeem.com/blog/2015/12/28/custom-dimentions-embedded-github-gists/) provides a solution so that we can force a scrollbar for gist embed. 

> * [ ]  Formulas are images
> 
> This is really critical for ML team in particular. How are we supposed to edit the formulas?! This is a strict requirement for ML to write blog posts - we need mathjax or any other native math rendering.
> 
> Besides, they are displayed HUGE on my Mac.

Looks like [MathJax](https://ulrik.is/writing/ghost-mathjax/) might be able to solve this issue. What do you think?  

> * [ ]  Problems with specific posts
> 
> https://blog.sourced.tech/post/id2vec/
> ![Screenshot 2019-03-20 at 15 57 50](https://user-images.githubusercontent.com/2793551/54694717-f607eb80-4b28-11e9-8e13-215bbb8ae7e3.png)

Fixed.

**Comment by vmarkovtsev** [comment] 2019-05-11 10:50
Addition: about 30% of the ported posts have an invalid date. Some have a wrong year, and some have a wrong month.

I am fixing everything myself since Victor gave me Admin permissions.

**Comment by vmarkovtsev** [comment] 2019-05-13 14:05
Status:

- Fixed descriptions using API
- Fixed authors using API and a manual pass over the teams
- Fixed the front images
- Fixed the dates
- I know how to fix code blocks, need to change the theme CSS

**Comment by vmarkovtsev** [comment] 2019-05-13 14:09
The tables were added using `<center>`, which is not included into HTML5. It works by a chance.
The CSS will have to be changed to properly center and resize.

**Comment by bzz** [comment] 2019-07-12 12:10
@vcoisne @vmarkovtsev not sure if that is the right place to rerport or what is the process with the new blog. 

But I noticed that the footer in the [recent posts](https://blog.sourced.tech/post/announcing-source-d-enterprise-edition-a-scalable-secure-and-extensible-data-platform-for-enterprises/) seems to be in the need of updating:

```
PRODUCT TEAM
DevRel team at source{d}: Francesc Campoy and Victor Coisne
```

**Comment by dpordomingo** [comment] 2019-07-12 13:30
I think it's because the signature of "product team" is defined that way, so it appears like that in [all posts written by Product](https://blog.sourced.tech/author/product/)

**Comment by vcoisne** [comment] 2019-07-15 07:22
Updated. @vmarkovtsev did you get a chance to update the code blocks ? If not we can ask Zuri to help.

**Comment by vcoisne** [comment] 2019-08-19 22:36
@vmarkovtsev Ping. Did you get a chance to make the changes you were looking for ? If not Zuri or Dmitry might be able to help.

**Comment by vcoisne** [comment] 2019-09-16 23:32
I created a separate issue to finalize this migration. https://github.com/src-d/landing/issues/463

Closing this one.

**Closed by vcoisne** 2019-09-16 23:32 UTC
